# Generated by Django 5.2.1 on 2025-06-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField()),
                ('version', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
