# Generated by Django 5.2.1 on 2025-06-09 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0002_aplicacion_evento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aplicacion',
            old_name='evento',
            new_name='categoria',
        ),
    ]
